[package]
name = "myls"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
clap = { version = "4.5.4", features = ["derive"] }
regex = "1.10.4"


[dev-dependencies]
tempfile = "3.2.0"
